### PR TITLE
Fixed a bug in text_parser.py

### PR DESCRIPTION
**Pull request by MapMaths**
Tested in Win10.
Fixed a `FileNotFoundError`

### CODE REVIEW

**Comment by MapMaths** [comment]
Excuse me, what's the file `text_logic_forms_pred.json` used for?

**Comment by MapMaths** [comment]
It seems that there will be two files in the folder after changing

**Comment by lupantech** [comment]
Hi Zimo,

In terms of content, text_logic_forms_pred.json is exactly as same as text_logic_forms.json. The text_parser.py generates a file with a different name just for distinguishing that it is a newly generated file.

**Comment by lupantech** [comment]
Hi Zimo,

In terms of content, text_logic_forms_pred.json is exactly as same as
text_logic_forms.json.
The text_parser.py generates a file with a different name just for
distinguishing
that it is a newly generated file.

Best regards,
Pan

**Comment by MapMaths** [comment]
Got it, thanks

**Comment by MapMaths** [comment]
Hi, I saw people who are asking questions in `Issues`, and since it is not for Q&A, I think it is better for you to open the `Discussion` section in GitHub. It is at `Settings/Options/Features`.
image
image
image
:D

**Comment by lupantech** [comment]
Thanks for your suggestion! I am glad to open the discussion channel.

**Comment by MapMaths** [comment]
NP. Also glad to be adopted

**Pull request merged**
